client:
	g++ client.cpp -o client -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network

server:
	g++ server.cpp -o server -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network


all: client server
