client:
	g++ client.cpp -o client -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network

server:
	g++ server.cpp -o server -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network

lua:
	g++ main.cpp -llua -ldl  -lstdc++fs -std=c++20 -o main 



all: client server
